-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE*sum(SALES_AMOUNT)) as SALES
from PRODUCT, OFFLINE_SALE
where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by PRODUCT_CODE
order by SALES DESC, PRODUCT_CODE