-- 코드를 입력하세요
SELECT
date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID,
USER_ID, SALES_AMOUNT
from ONLINE_SALE
where date_format(SALES_DATE, '%Y-%m') = '2022-03'

union all

SELECT
date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID,
null as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where date_format(SALES_DATE, '%Y-%m') = '2022-03'
order by SALES_DATE, PRODUCT_ID, USER_ID


# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
# UNION ALL
# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID