-- 코드를 입력하세요
SELECT
REST_INFO.REST_ID,
REST_NAME,
FOOD_TYPE,
FAVORITES,
ADDRESS,
round(avg(REVIEW_SCORE), 2) as SCORE
from REST_INFO, REST_REVIEW
where REST_INFO.REST_ID = REST_REVIEW.REST_ID and ADDRESS like '서울%'
group by REST_INFO.REST_ID
order by SCORE DESC, FAVORITES DESC