-- 코드를 입력하세요
SELECT 
FOOD_PRODUCT.PRODUCT_ID, PRODUCT_NAME, sum(PRICE*AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT,FOOD_ORDER
where FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
and PRODUCE_DATE like '2022-05%'
group by FOOD_PRODUCT.PRODUCT_ID
order by TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID