-- 코드를 입력하세요
SELECT USER_ID,	NICKNAME, sum(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD, USED_GOODS_USER
where USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID and STATUS = 'DONE'
group by NICKNAME
having TOTAL_SALES >= 700000
order by TOTAL_SALES