-- 코드를 입력하세요
SELECT 
MEMBER_NAME,
REVIEW_TEXT,
date_format(REVIEW_DATE, '%Y-%m-%d')as REVIEW_DATE
from MEMBER_PROFILE, REST_REVIEW
where 
MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
and 
MEMBER_PROFILE.MEMBER_ID = (select MEMBER_ID from REST_REVIEW group by MEMBER_ID order by count(MEMBER_ID) DESC limit 1)
order by REVIEW_DATE, REVIEW_TEXT
