-- 코드를 입력하세요

select BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK
where CATEGORY='인문' and PUBLISHED_DATE like '2021%'
order by PUBLISHED_DATE


# SELECT BOOK_ID,	DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
# FROM BOOK
# WHERE CATEGORY = '인문' AND DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') between '2021-01-01' AND '2021-12-31'
# ORDER BY PUBLISHED_DATE