-- 코드를 입력하세요
SELECT 
    USED_GOODS_BOARD.TITLE,
    USED_GOODS_BOARD.BOARD_ID,
    USED_GOODS_REPLY.REPLY_ID,
    USED_GOODS_REPLY.WRITER_ID,
    USED_GOODS_REPLY.CONTENTS, 
    DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE 
    USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
    AND DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY 
    USED_GOODS_REPLY.CREATED_DATE ASC, 
    USED_GOODS_BOARD.TITLE ASC;
    
    
#     SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d')
# FROM USED_GOODS_BOARD AS A , USED_GOODS_REPLY AS B
# WHERE A.BOARD_ID = B.BOARD_ID
# AND A.CREATED_DATE LIKE '2022-10%'
# ORDER BY B.CREATED_DATE, A.TITLE;